name: build

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs: 
    build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: [3.9]
      env:
          USING_COVERAGE: "3.9"

      steps:
          - name: Checkout sources
            uses: actions/checkout@v2

          - name: Set up Python v ${{ matrix.python-version }}
            uses: actions/setup-python@v2
            with:
                python-version: ${{ matrix.python-version }}

          - name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                python -m pip install black coverage flake8 mccabe mypy pylint pytest tox tox-gh-actions pytest-cov poetry
          - name: Run tox and build
            run: |
                make build
          - name: Generate Report
            run: |
              coverage run -m spyc.spyc

          # - name: "Upload coverage to Codecov"
          #   uses: codecov/codecov-action@v1
          #   if: contains(env.USING_COVERAGE, matrix.python-version)
          #   with:
          #     token: ${{ secrets.CODECOV_TOKEN }} 
          #     fail_ci_if_error: true