name: build

on:
    push:
    pull_request:
        branches: [main]

jobs: 
    build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: [3.9]
      env:
          USING_COVERAGE: "3.9"

      steps:
          - name: Checkout sources
            uses: actions/checkout@v2

          - name: Set up Python v ${{ matrix.python-version }}
            uses: actions/setup-python@v2
            with:
                python-version: ${{ matrix.python-version }}

          - name: Install Poetry and dependencies
            uses: snok/install-poetry@v1.1.6
          - run: |
              pip install -U pip
              poetry install
            env:
              POETRY_VIRTUALENVS_CREATE: false

          - name: Run tox and build
            run: |
                make build

          - name: Generate Coverage Report
            run: |
              coverage run -m spyc.spyc

          # - name: "Upload coverage to Codecov"
          #   uses: codecov/codecov-action@v1
          #   if: contains(env.USING_COVERAGE, matrix.python-version)
          #   with:
          #     token: ${{ secrets.CODECOV_TOKEN }} 
          #     fail_ci_if_error: true